# Generated by Django 6.0.6 on 2026-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_address_user_createat_user_loginat_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="createAt",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="loginAt",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
