# Generated by Django 6.0.6 on 2026-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_createat_alter_user_loginat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.FileField(blank=True, null=True, upload_to="profile"),
        ),
    ]
