# Generated by Django 6.0.6 on 2026-08-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="createdAt",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
