# Generated by Django 6.0.6 on 2026-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="COD", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
