# Generated by Django 6.0.6 on 2026-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_order_address_order_full_name_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
