# Generated by Django 6.0.6 on 2026-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
