# Generated by Django 6.0.6 on 2026-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_product_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="produtc"),
        ),
    ]
