# Generated by Django 6.0.6 on 2026-08-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
